CREATE TABLE HELLO(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(255) DEFAULT NULL,
    ld DATE DEFAULT NULL
);

CREATE TABLE Student(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    country VARCHAR(255) DEFAULT NULL,
    mentor VARCHAR(255) DEFAULT NULL,
    major VARCHAR(255) DEFAULT NULL,
    name VARCHAR(255) DEFAULT NULL
);

CREATE SEQUENCE hibernate_sequence;